### ISSUE TITLE
Ongoing voice call destroyed when a third call is rejected

### ISSUE THREAD

**Issue by nicolettemanas** [twilio/voice-quickstart-objc#44] opened 2017-07-20 07:42 UTC
Hi Twilio Team, 

Currently using TwilioVoice 2.0.0-beta12. Please refer to the ff steps to replicate the issue:
1. Ongoing call between user1 and user2
2. User3 tries to call user1
3. Call invite from user1 gets rejected due to the ongoing call (as opposed to being ignored in the sample app)

Result: Audio disappeared from the ongoing call between user1 and user2

I have included the verbose Twilio logs [here](https://github.com/twilio/voice-quickstart-objc/files/1161521/twiliovoice-logs.txt).

I added ` [self.callInvite reject];` upon receiving an invite when there is an ongoing call as seen in the log:

```
callInviteReceived:
Already an active call.
   >> Rejecting call from 83782
```

Hope this helps.
Thanks!

**Comment by ceaglest** [comment] 2017-07-20 16:30
Hi @nicolettemanas,

Thank you for the report! The iOS SDK currently has a restriction of one active Call at a time, but it looks like it is not behaving as expected when the 3rd call is rejected. I will look into this, and respond to the ticket once we know more.

Thanks,
Chris Eagleston

**Comment by nicolettemanas** [comment] 2017-07-21 06:01
Thanks @ceaglest 
If it helps, we encountered a somewhat similar [issue](https://github.com/twilio/voice-callkit-quickstart-objc/issues/7) in beta6.

**Comment by ceaglest** [comment] 2017-07-22 01:25
Hi,

I tried reproducing this issue using 2.0.0-beta13 by modifying ObjCVoiceQuickstart & ObjCVoiceCallKitQuickstart to reject instead of ignore invites. After making this change I was able to reject an invite without causing the active voice call to end. We also have test cases which do this automatically as part of our integration test suite, and they are currently passing.

However, there is clearly something fishy going on in the logs you provided. I can see that right around the time that the rejection starts the audio device is closed / stopped.

> 2017-07-20 15:23:06.971822 ObjCVoiceCallKitQuickstart[504:106973] [INFO TVORejectCallCommand] Call URI: sip:None@chunderm.gll.twilio.com;transport=tls
2017-07-20 15:23:06.972282 ObjCVoiceCallKitQuickstart[504:106973] PJSIP(4):   pjsua_call.c !Making call with acc #0 to sip:None@chunderm.gll.twilio.com;transport=tls
2017-07-20 15:23:06.972593 ObjCVoiceCallKitQuickstart[504:106946] PJSIP(4):    pjsua_aud.c !.Closing iPhone IO device sound playback device and iPhone IO device sound capture device
2017-07-20 15:23:06.997677 ObjCVoiceCallKitQuickstart[504:106946] PJSIP(4): coreaudio_dev.  .core audio stream stopped
2017-07-20 15:23:07.075377 ObjCVoiceCallKitQuickstart[504:106946] [DEBUG TwilioVoice] Inside removeFromActiveCalls:, no matching active call for <TVOCall: 0x17411d2e0>

I will continue investigating this issue, but unfortunately I don't have a solution for you just yet. Our internal ticket for this is `CLIENT-3873`. A few more questions if you have the chance:

1. How reproducible is the bug (50% of the time, 100% etc)?
2. Is there a particular device or OS that is needed to reproduce the issue?

Though we did release 2.0.0-beta13 this week, it didn't contain any changes to call management / invite rejection so I expect you would see the same issue if you upgrade from beta12.

Regards,
Chris Eagleston

**Comment by nicolettemanas** [comment] 2017-07-24 08:27
Hi @ceaglest, 

Confirming that this indeed doesn't happen in 2.0.0-beta13. 
Regarding your questions:

1. It happens 100% of the time (using 2.0.0-beta12) with the ff devices: 
2. iPhone6s(iOS10.1.1), iPhone5(iOS10.2.1), iPad mini(iOS9.3.5), iPad air(iOS10.1.1)

We will proceed testing in 2.0.0-beta13 for now.

Thanks,
Jean

**Comment by ceaglest** [comment] 2017-07-24 20:33
Hi @nicolettemanas,

Does the issue occur with or without CallKit integration? I noticed that your logs were using the CallKit enabled example, but the iPad Mini running iOS 9.3.5 does not support CallKit.

Once I hear back from you on #48 I will likely merge it into this issue.

Best,
Chris Eagleston

**Comment by nicolettemanas** [comment] 2017-07-25 00:59
Hi @ceaglest ,

The issue happens with or without CallKit integration. I build the app on the iPad Mini iOS 9.3.5 using the target without CallKit integration (**ObjCVoiceQuickstart**). As for devices running iOS10 and up, I use **ObjCVoiceCallKitQuickstart**

Thanks,
Jean

**Comment by ceaglest** [comment] 2017-07-26 21:14
Thanks for the additional info. I've raised this issue to our QA team since I was not able to reproduce locally with the devices that I had on hand, and the rejection change to the QS's that I mentioned.

**Comment by ceaglest** [comment] 2017-08-03 23:23
Hi Jean,

Our QA team also tried to reproduce this issue (using 2.0.0-beta13) but they were not able to. I can see from your logs that something is definitely going wrong since the audio should not shut down like that.

Can you confirm that the modifications you made to the QS are the same as what is on my branch?

https://github.com/twilio/voice-quickstart-objc/tree/issue/48-ongoing-call-disconnect-missed

Is there anything special about your TwiML app?

Regards,
Chris Eagleston

**Comment by nicolettemanas** [comment] 2017-08-04 00:54
Hi @ceaglest ,

Sorry, I confirmed that this **_does not_** happen and is already fixed in beta13. 😅   I think you missed it in my previous comments. Sorry for not being clear about this. 

Best regards,
Jean

**Comment by ceaglest** [comment] 2017-08-04 00:56
Oh boy, I think I missed the contraction in your message a few up. 😰 

So at this point my findings, yours, and our QA teams match. Closing this out!

**Closed as completed by ceaglest** 2017-08-04 00:56 UTC
Labels: bug
