### ISSUE TITLE
incoming call has no voice

### ISSUE THREAD

**Issue by wazrx** [twilio/voice-quickstart-objc#73] opened 2017-12-19 11:16 UTC
i try to use the quick start demo to make a call to a client with client identify, the client can receive and accept the incoming call, but can not hear the both side voice, i don't know what is the problem?

**Comment by bobiechen-twilio** [comment] 2017-12-19 17:32
Hi @wazrx 

Thanks for choosing the Voice SDK and I am sorry you are experiencing this issue.
I will need your help and provide us some information so that we can take a deeper look and help you with the audio problem:
- Does the same audio issue happen in your environment (device, network) with the quickstart that we provided?
- Voice SDK version: I am assuming you are already using the latest version (`v2.0.0`) but just in case. We have added some very good improvement with audio device control in the latest release.
- Call-SID: you can find the Twilio Call-SID in `TVOCallInvite.callSid` or `TVOCall.sid`.
- The SDK log when the audio issue happened. `.verbose` would be the best.

Please note that you should not post any of your account credentials (Twilio Account SID, API key/secret) here publicly. You should be able to find my email address ;) We'll get back to you once we figure out the root cause.

Thanks.
-bobie

**Comment by wazrx** [comment] 2017-12-20 04:07
today i found the problem, if i open the SSR on one mobile, the no sound problem will happen, when i shut down the SSR 😳 ，everything become OK, but i still has some question， i try to connect your sale team in twilio homepage， and i send many emails and leave my phone numbers， but nobody connect to me😳， you are the first gentleman i connect successfully........

**Comment by bobiechen-twilio** [comment] 2017-12-20 21:39
Hi @wazrx 

I am sorry that you didn't receive timely help but I am also glad that you managed to solve the problem. Just curious, what does the SSR stand for?

Thanks.
-bobie
Programmable Voice iOS SDK
Twilio SDK Engineering

**Comment by bobiechen-twilio** [comment] 2018-01-02 17:51
Hi @wazrx,

I am assuming the SDK is working well with your application and closing this ticket for now.
Please feel free to open a new ticket if you run into any issue in the future.

Thanks.
-bobie

**Closed as completed by bobiechen-twilio** 2018-01-02 17:51 UTC
Labels: bug

**Comment by bart2016** [comment] 2018-03-14 02:22
@wazrx thanks for the follow up! It helps a lot.

@bchen-twilio  SSR stands for shadowsocksR.

**Comment by wazrx** [comment] 2018-03-14 02:32
@bart2016 yes,SSR means shadowsocksR, i forget to reply this, i am glad to help you, are you Chinese developer ? we can QQ or Wexin to discuss twilio....
