### ISSUE TITLE
Server installation issue

### ISSUE THREAD

**Issue by vijayaa** [twilio/voice-quickstart-objc#37] opened 2017-06-16 04:56 UTC
When i execute the below command
pip install -r requirements.txt

 **i am getting the below error**

`_Collecting wsgiref==0.1.2 (from -r requirements.txt (line 9))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-a5do1_is/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-build-a5do1_is/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-a5do1_is/wsgiref/ `_

**Comment by bobiechen-twilio** [comment] 2017-06-16 21:39
Hi @vijayaa 

What is the version of macOS and python on your machine?
I have python 2.7.11 on my macOS Sierra 10.12.4 on my machine. I tried the pip install again and it worked for me.
If this keeps happening, could you try to re-install python using this?
```
$> brew install python
```

thanks
-bobie

**Comment by bobiechen-twilio** [comment] 2017-06-21 23:04
Hi @vijayaa 

It seems the issue is caused due to the compatibility between standalone `wsgiref` and python3. To ensure the backward compatibility with python2, unfortunately we cannot just remove the `wsgireg` lib from the requirements.txt now, but I've tried deploying without it and was able to finish the installation and able to hit the `/accessToken` endpoint.

The `wsgiref` in python3 should be good enough. You can remove it from the requirement.txt if the destination platform has python3.

Thanks.
-bobie

**Comment by bobiechen-twilio** [comment] 2017-09-07 16:52
Hi @vijayaa 

We've updated the [python server quickstart](https://github.com/twilio/voice-quickstart-server-python) and added a `runtime.txt` file to explicitly specify the python version. This should address the compatibility issue between python and `wsgiref` library. It would be great if you could pull the latest server quickstart and give it another try.

I am going to close this ticket but please feel free to reopen or create new ticket if you run into any issue in the future. Thanks.

-bobie

**Closed as completed by bobiechen-twilio** 2017-09-07 16:52 UTC
