### ISSUE TITLE
Beta-9 DTMF tones are not transmitted

### ISSUE THREAD

**Issue by geoffliddiard** [twilio/voice-quickstart-objc#30] opened 2017-05-13 07:09 UTC
Just updated to beta-9 and noticed that DTMF tones aren't being transmitted by the TVOCall sendDigits method, local audio is a nice addition and works great though!

Cheers

**Comment by bobiechen-twilio** [comment] 2017-05-13 16:01
oh oh this is definitely not good...
@geoffliddiard could you share the details of the call participants?
I've just tried to use the voice mobile client to call a Twilio JS client and a PSTN number and I was able to hear DTMF at the other end. Maybe I missed the case or some steps you did?

Thanks for giving beta9 a try.

cheers
-bobie

**Comment by geoffliddiard** [comment] 2017-05-15 08:52
@bchen-twilio sure both clients are using native SDKs, outgoing call was placed from a device using Android 2.0.0-beta4 and incoming was received by iOS beta-9. The call is routed through our system using Twiml to gather a digits response before connecting the clients. Hope that helps!

Cheers

**Comment by bobiechen-twilio** [comment] 2017-05-15 16:55
Thanks @geoffliddiard.

The changes we added in beta9 is mainly for tone playback when sending digits from local client, which should have nothing to do with the case when DTMF is received from the other call participant. However I did try with the TwilioClient 1.2 iOS SDK and DTMF tones can be heard clearly when receiving digits, while for the Voice SDK the tones seemed to be short and kind of distorted.

I'll do some tests today without the changes and see if this is a regression, otherwise you've found a big, long existing bug. Keep you updated.

cheers
-bobie

**Comment by bobiechen-twilio** [comment] 2017-05-15 19:34
Hi @geoffliddiard 
Sorry fro the confusion I am going to make, but unfortunately the Twilio Voice mobile SDKs actually do not support receiving/collecting DTMF digits at the moment, but only sending. The low-volume distorted sound I heard in my previous testing are just a feedback from another client's speaker.

Let me know if you have further questions.

cheers
-bobie

**Comment by eabait** [comment] 2017-06-06 15:33
Hey @bchen-twilio 

I can confirm what @geoffliddiard says. I've been trying to send DTMF tones using `sendDigits` method:
```
  if (self.call && self.call.state == TVOCallStateConnected) {
    [self.call sendDigits:digits];
  }
```
And that only works (digits are received in the action of the Gather) when using version beta8. Using beta9 or beta10 doesn't work.

Regards!
Esteban

**Comment by bobiechen-twilio** [comment] 2017-06-06 16:54
Hi @eabait 

Thanks for reporting this.
It sounds like you are using Twilio JS Client on the receiving end, right?
Sorry that the recent updates are causing you troubles. I'll try and see if I can find the balance between the original and new DTMF implementation and make sure it's back to the working state.

Will keep you updated.
Would it be okay if I send SDK patches for you to try once I have any?

Thanks.
-bobie

**Comment by eabait** [comment] 2017-06-06 17:02
I'm using this CocoaPod on the receiver end: https://github.com/twilio/cocoapod-specs/tree/master/TwilioVoice

**Comment by bobiechen-twilio** [comment] 2017-06-06 17:08
So the receiver is also an iOS Programmable Voice client?

**Comment by eabait** [comment] 2017-06-06 20:18
Sorry for the late response. The receiver is an iOS Programmable Voice client. The call is initiated on the server side, something like this: `client.calls.create(url=request.url_root + 'visitor/ask', method="GET", to='client:'+to, from_='client:'+caller)`

**Comment by bobiechen-twilio** [comment] 2017-06-06 20:21
Thanks for the clarification @eabait.
Could you tell us more about next? who sends the digits (I am guessing it's one of the iOS client calling `call.sendDigits`) and who is receiving, and how.

**Comment by eabait** [comment] 2017-06-07 13:20
Yes, the receiver sends the digits ([self.call sendDigits:digits]), and they are received by the Python script as the `Digits` parameter in the request.

**Comment by bobiechen-twilio** [comment] 2017-06-07 18:16
Hi @eabait 

Sorry I don't think I am following your last comment.
Is it like this?
- iPhone A has Programmable Voice SDK running on it and registered as `Alice`, and iPhone B registered as `Bob`
- `Alice` uses `TwilioVoice.call:params:delegate:` to establish a call with `Bob`
- In the call, `Alice` sends DTMFs to `Bob` by calling `TVOCall.sendDigits:`

Please correct me if I am understanding this wrong, but unfortunately the Programmable Voice mobile clients don't have the capability to collect DTMF digits.

Could you share more details about your python script or TwiML that is gathering the digits? would love to know how the DTMF digits are being sent and received or dispatched.

Thanks.
-bobie

**Comment by bobiechen-twilio** [comment] 2017-06-08 00:57
Hi @eabait 

I think I've found the bug and fixed it. Now it's working great again with <Gather>.
Could you shoot me an email so I can provide you a patch to try?

Thanks.

**Comment by eabait** [comment] 2017-06-08 22:03
@bchen-twilio send it to estebanabait at gmail . com

**Comment by bobiechen-twilio** [comment] 2017-06-08 22:13
Sent you the patch ;)

**Comment by girtis** [comment] 2017-08-27 06:06
Looks like this was successfully resolved. Closing.

**Closed as completed by girtis** 2017-08-27 06:06 UTC
