### ISSUE TITLE
CallKit - Screen not dimming when making calls

### ISSUE THREAD

**Issue by fabriziomoscon** [twilio/voice-quickstart-objc#56] opened 2017-09-11 18:53 UTC
### Description
When using the latest SDK with CallKit and receiving calls the proximity sensor is triggered and the screen locked/dimmed when approaching my face, but the screen keeps on when making calls.

### Steps to Reproduce

1. make a call
2. place the device close to the face or cover the proximity sensor with your hand
3. the screen is still on

#### Voice iOS SDK

Experienced since pod `2.0.0-beta10` 

#### iOS Version

`10.3.3`

#### iOS Device

`iPhone 6`

**Comment by bobiechen-twilio** [comment] 2017-09-11 19:33
HI @fabriziomoscon 

I tried the latest beta15 but was not seeing the issue both when making or accepting calls.
Could you share with us how & when is the proximity-sensor being turned on and off in the native integration layer of the framework?
I tried to enable the sensor when getting the `callDidConnect:` callback and tried to disable it when getting the `callDidDisconnect:` callback by using
```
  UIDevice* device = [UIDevice currentDevice];
  device.proximityMonitoringEnabled = YES;  // or NO
```

-bobie

**Comment by fabriziomoscon** [comment] 2017-09-11 19:59
I see,
I am using the react native integration, but usually that doesn't prevent me to follow this repository almost 1:1.

I did not try any additional expression like the 2 lines you posted. I assumed that CallKit was managing the proximity automatically since it is triggered when answering.

If I understand correctly @bchen-twilio you suggest to use the 2 lines you wrote explicitly?

**Comment by bobiechen-twilio** [comment] 2017-09-13 01:50
HI @fabriziomoscon 

Sorry for the delay of my responding back to you.
Yes, I also thought that CallKit framework should just take care of the proximity sensor but apparently it doesn't seem like so. There isn't documentation from Apple showing how to configure the framework with the sensor.

We'll keep tracking this issue and see if this is due to the way the SDK configures the `AVAudioSession`. For now yes, I would suggestion you use the lines in your application.

Thanks
-bobie

**Comment by bobiechen-twilio** [comment] 2018-01-09 20:07
I am assuming the issue is resolved and closing the issue for now.

**Closed as completed by bobiechen-twilio** 2018-01-09 20:07 UTC

**Comment by fabriziomoscon** [comment] 2018-01-10 09:46
yes thanks, I have included those two lines you pasted, and everything works fine.
