### ISSUE TITLE
Notification not receiving after app close

### ISSUE THREAD

**Issue by volkoffindia** [twilio/voice-quickstart-objc#102] opened 2018-04-20 09:20 UTC
Hello
I am doing VOIP with twillo calling. Application is allow notification while app is background or foreground. we are not received notification while app is close. I have written code in AppDelegate..
But register with Push after socket is connected.

**Comment by bobiechen-twilio** [comment] 2018-04-20 17:02
Hi @arvd 

Don't worry, it's probably some small detail that we've missed here.
- Are you able to get successful result when calling the `TwilioVoice.register()` method?
- Are you able to get call notifications when the app is active?
- Can you provide us Call SIDs when the app is unable to respond to the notification if it is terminated? you can find the Call SID from the `TVOCall` object (on the caller side) or the [Call Logs in the Voice Dashboard](https://www.twilio.com/console/voice/calls/logs).

Thanks,
-bobie

**Comment by volkoffindia** [comment] 2018-04-23 05:26
Hello Bobie
Yes I am getting successful register Twilio and also get token.
Yes I get notification while all is active and background.
Here is my SID: CR14a04681443dd5dfc564cad97e86cc3f

Thanks,
Arvind

**Comment by volkoffindia** [comment] 2018-04-23 05:31
and I am also see Call Logs in Twilio account.. Here I attached screenshot.when app close showing in call logs but notification doesn't appearer. 
<img width="1026" alt="screen shot 2018-04-23 at 10 59 34 am" src="https://user-images.githubusercontent.com/3807011/39108386-8aeaa1d2-46e5-11e8-984f-d59f3dbcdcbb.png">

**Comment by bobiechen-twilio** [comment] 2018-04-23 18:31
Hi @arvd 

Thanks for providing the Push Credential. We've checked the database with it but things looks perfectly functioning. One more thing you can help us check - (assuming that your app is written with Xcode 9) does your app project have the background mode configured properly in the plist to support `audio` and `voip`? you can find more instruction in the [quickstart README](https://github.com/twilio/voice-quickstart-objc#9-configure-xcode-project-settings-for-push-notifications).

-bobie

**Comment by volkoffindia** [comment] 2018-04-24 04:54
Hello Bobie
Yes I am using Xcode 9.2 and my application source code is 2 years old but I am using Xcode 9.2 now.
and yes I have added background and voip setting in plist.

**Comment by bobiechen-twilio** [comment] 2018-04-24 16:24
Hi @arvd 

How does your app show the incoming call when it gets a call notification while it's in the background? do you use UILocalNotification or do you report the call to the CallKit framework?
If it is not too much trouble, could you also try using the quickstart and see if the same issue is happening? just want to first make sure your account credentials and the notifications settings are correctly configured.

Thanks
-bobie

**Comment by volkoffindia** [comment] 2018-04-25 05:06
Hello Bobie
I am using call kit framework.. it was difficult for me to integrating in quickstart demo. Yes credentials are correctly configured.. I received call when background and foreground..

**Comment by bobiechen-twilio** [comment] 2018-04-25 16:41
Thanks and no worries @arvd, looks like your credentials are functioning correctly.
To try the (CallKit) quickstart, simply replace a couple of items in the project:
- Bundle ID
- Access Token URL
then launch the app and register. Closing the app and ensure call notification can still be received and incoming call alert is shown to the user is always one of the validation steps that we perform in every version.

**Comment by bobiechen-twilio** [comment] 2018-05-29 20:05
Hi @arvd 

Just want to touch base - have you found the root cause that your app is not getting call notification when it is terminated?

-bobie

**Comment by ankitpatelka** [comment] 2018-05-31 07:35
Hello Bobie/[@arvd](https://github.com/arvd),

I am also facing same issue. 
In my case i am using quick start demo app, now in this app i have just put single page interface ahead of 'Viewcontroller' for calling automatic to fix userid. i am able to call using that functionality. 

But now when i close app(killed) and call to that user from another device, i am not getting incoming VOIP call from call-kit(APP is killed not active). 

Once i open call and register with VOIP and perform fetch access token. i am able to get same call.
in both case app is in foreground/background.

And another finding, if i run raw quick start app it will works fine. Any quick suggestions so i can fix this.

**Comment by bobiechen-twilio** [comment] 2018-05-31 16:44
Hi @ankitpatelka 

One suggestion is to try using the quickstart and add the similar UI flow to it, then see at which step the app stops showing incoming calls when it's not in the foreground.

**Comment by ankitpatelka** [comment] 2018-06-04 05:56
Thanks Bobie it was worked for me, that is issue related Configuration of Callkit (CXProviderConfiguration).

**Comment by bobiechen-twilio** [comment] 2018-06-04 16:46
Awesome @ankitpatelka 👍

**Closed as completed by bobiechen-twilio** 2018-06-04 16:46 UTC
Labels: help wanted

**Comment by bobiechen-twilio** [comment] 2018-06-05 16:59
Hi @ankitpatelka 

Can you share how you fixed the issue with the CallKit config? this might be helpful also for other SDK users.

Thanks!
-bobie
